<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\external\FNA\FNA.Core.csproj" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\TSCharacters.txt" />
  </ItemGroup>

</Project>
